### ISSUE TITLE
Replace images used for custom blocks/pullouts

### ISSUE THREAD

**Issue by willingc** [jupyter4edu/jupyter-edu-book#115]
Related to #114. The images from Bookdown are a bit 90s looking. Let's use font awesome images and create consistent usage definitions.

**Comment by labarba** [comment]
One possible source: Google Design open-source glyphs:

https://github.com/google/material-design-icons/releases/tag/1.0.0

**Comment by labarba** [comment]
https://material.io/tools/icons/?style=baseline

**Comment by willingc** [comment]
Thanks @labarba. These look good and don't require conversion which the font-awesome ones do.

**Comment by dsblank** [comment]
Shall I replace the pictures, and update the text with the new block format?

**Comment by willingc** [comment]
Hang tight @dsblank. Incoming PR.

**Comment by dsblank** [comment]
Even better, @willingc !
