### ISSUE TITLE
[Ch 4] Order of pedagogical patterns

### ISSUE THREAD

**Issue by lheagy** [jupyter4edu/jupyter-edu-book#123]
I think we can help the readers a bit by organizing the chapter so that similar patterns are grouped together. Here is a suggestion and I look forward to hearing thoughts on it.

(The extra line break is a visual cue to indicate items I suggest we group together. The order of the groups could easily be changed as can the order within the groups. Roughly, for the internal ordering, I tried to go with increasing complexity).  

--- 
- Introduction
---
- Shift-Enter for the win
- Fill in the blanks
- Target Practice
- Twiddle, tweak and frob
---
- Notebook as an app 
- Win-day-one
- Top-down sequence
--- 
- Two bites at every apple
- Coding as translation
- Symbolic math over pencil + paper
- Replace analysis with numerical methods
- The API is the lesson
- Proof by example, disproof by counterexample
---
- The world is your dataset
- Now you try (with different data or process)
- Connect to external audiences
- There can only be one
---
- Hello, world!
- Test driven development
- Code reviews
- Bug hunt
- Adversarial programming
---

**Comment by moorepants** [comment]
Looks fine. I'd just reorder and if it needs tweaking later, people can do it.

**Comment by jedbrown** [comment]
LGTM. Would it make sense to group them under sub-headings?

**Comment by lheagy** [comment]
Sounds good! I can take a crack at it. I was thinking about sub-headings, but there is definitely blurring between the groups, so I hesitate to draw too much of a line between them. I think the main thing is to just help the reader by having like things close together.... my 2 cents :)
