### ISSUE TITLE
How was this book produced?

### ISSUE THREAD

**Issue by ofenerci** [jupyter4edu/jupyter-edu-book#153]
Thank you all putting such a wonderful book on a web. I wonder how the book was produced (i.e., which software and editors were used?). How was converted into Jupyter notebooks.

Bests,

**Comment by jedbrown** [comment]
We used [Bookdown](https://bookdown.org/) to write this book. The complete source is in this repository. Since the source is all markdown, each contributor used whichever editor they prefer.

**Comment by ratnanil** [comment]
I'm a bit surprised that you didn't use sphinx to create this book. I specifically landed here since I'm creating a course curriculum using jupyter notebooks with sphinx / nbsphinx and hoped to find help here.

**Comment by jedbrown** [comment]
Sphinx was discussed, but we preferred the features and presentation of Bookdown for this project.

**Comment by ratnanil** [comment]
Very interesting, thanks for your answer. I'm coming from the R world (and am an avid markdown / bookdown user) and I'm struggling with jupyter notebooks / sphinx  environment. I kept trudging on since I figured "when in Rome..."  Now, apparently, I see the Romans use R-tools!
