### ISSUE TITLE
Authorization to merge?

### ISSUE THREAD

**Issue by moorepants** [jupyter4edu/jupyter-edu-book#57]
Can all of the authors get merge rights? I don't seem to have permission.

**Comment by willingc** [comment]
Seems reasonable to me as everything requires a review prior to merge. @labarba @kyleniemeyer thoughts?

**Comment by labarba** [comment]
We removed write permissions after setting up the automatic sync with Zenodo to mint a DOI with a tagged release, as a safety. We saw no way to protect from someone making a release, by a miscalculation or gaffe. Because of branch protection, we thought it wouldn't make a difference (every change has to go through PR anyway). But I see the issue about merge rights. Unsure how to proceed.

**Comment by willingc** [comment]
Perhaps for now add @moorepants to write. Others can request write permissions if desired.

**Comment by kyleniemeyer** [comment]
OK, I've added an "authors" team that includes all of the authors from the sprint (that were already members of the org); these people *should* have PR merge/approval rights, while `master` is still protected. 

However, it looks like GitHub doesn't actually have a way to protect tags, aside from restricting write access—and doing that restricts the ability to merge, I think.

**Comment by kyleniemeyer** [comment]
(but @labarba @willingc let me know if you'd prefer a different configuration)

**Comment by willingc** [comment]
Sounds good @kyleniemeyer. Thanks!

**Comment by moorepants** [comment]
Thanks!

**Comment by moorepants** [comment]
I'm still seeing this even on reviewed PRs:
![selection_344](https://user-images.githubusercontent.com/276007/49391432-82101780-f6e0-11e8-9eb6-aba6762662b6.png)

Is there something my end I must do to be "authorized"?

**Comment by willingc** [comment]
Weird. @moorepants I will look into the settings. In the meanwhile, check your email and spam folder to see if you need to accept and GitHub authorizations.

**Comment by moorepants** [comment]
I'll dig around, may have missed an email.

**Comment by willingc** [comment]
@moorepants I've adjusted the repo permissions so that only authors have write permissions to merge. Please let me know if that doesn't help.

I've also update the org collaborator team so the default behavior team-wide is read not write. Write privileges can be extended as needed by repo.

**Comment by moorepants** [comment]
I'm still seeing "The base branch restricts merging to authorized users." on #94 for example. It seems I am a member of the "authors" team.

**Comment by willingc** [comment]
Just updated the branch protection to allow authors not just admins. Thanks for the detailed error message. @moorepants give it 10 minutes and then try to merge #94.

**Comment by dsblank** [comment]
Thanks @moorepants, @kyleniemeyer , and @willingc ... looking forward to new powers.... bwahahaha.

**Comment by moorepants** [comment]
I am still seeing "The base branch restricts merging to authorized users." on #94. I opened in a Firefox private window and logged into Github to ensure it was nothing in my cache.

**Comment by dsblank** [comment]
Me too. No superpowers.

**Comment by willingc** [comment]
@dsblank @moorepants I've added admin privileges now to the author team as well (instead of just write). I :heart: GitHub permissions. Regular UNIX ACL would be an upgrade.

**Comment by willingc** [comment]
Please give it another try.

**Comment by willingc** [comment]
OK @moorepants now has supreme universe powers. @dsblank If you do as well, please close this issue :smile:

**Comment by dsblank** [comment]
Oh, yeah! Thanks, @willingc
