### ISSUE TITLE
Determine font for PDF

### ISSUE THREAD

**Issue by willingc** [jupyter4edu/jupyter-edu-book#98]
This issue is a follow-up from discussion on PR #94. 

The current font setting for the PDF does not render/support Unicode well. Should we change fonts or avoid Unicode characters? These are questions that to discuss in this issue.

[Jed's comment](https://github.com/jupyter4edu/jupyter-edu-book/pull/94#discussion_r238419333) and other responses provide additional insights.

**Comment by rwest** [comment]
Putting aside unicode / LaTeX / etc., yes we should change fonts :-)

I quite like Palatino. What are other people's favorites?

**Comment by dsblank** [comment]
I agree about changing the defaults to something better (and also refining the config settings if possible to give a better title sheet).

But I think it would be better to avoid using unicode where we can.

**Comment by willingc** [comment]
Looking at fonts/typography, it would be helpful to also consider accessibility. Here is one option: https://designsystem.digital.gov/components/typography/

**Comment by willingc** [comment]
Palatino looks good to me. It's a definite improvement to the current font. Any objections to using this for PDF version?

**Comment by jedbrown** [comment]
With XeTeX, we'd want an OTF/TTF rather than a Type-1. This is an extension of Palatino to greater unicode coverage: http://www.gust.org.pl/projects/e-foundry/tex-gyre/pagella

**Comment by willingc** [comment]
Interesting @jedbrown. Tried to change the font to your recommended font. I need more tex-fu to set bookdown correctly for it. The build isn't finding the library. Will need suggestions on #105 to amend.

**Comment by jedbrown** [comment]
Palatino is also not installed on Travis (failure in #105). I used other OTF fonts by adding `mainfont: Source Serif Pro` to index.Rmd. It looks like you can `apt install fonts-texgyre`. You can get the proper name by running `otfinfo -i /path/to/font-name.otf`; in this case you'd then use `mainfont: TeX Gyre Pagella`. I can test it in the morning if needed.
