### ISSUE TITLE
Callouts don't render in the PDF in any special way

### ISSUE THREAD

**Issue by moorepants** [jupyter4edu/jupyter-edu-book#99]
Compare HTML:
![selection_347](https://user-images.githubusercontent.com/276007/49401800-0bcdde00-f6fd-11e8-923f-4b4c174a7ce4.png)
to PDF:
![selection_348](https://user-images.githubusercontent.com/276007/49401806-12f4ec00-f6fd-11e8-8e04-e51e928c36e4.png)

**Comment by dsblank** [comment]
There is a section called "Custom blocks" here https://rdrr.io/github/rstudio/bookdown/f/inst/examples/02-components.Rmd that describes I think what we want to do (e.g., change our html tables to these blocks). Types include:

* rmdcaution
* rmdtip
* rmdwarning
* rmdimportant
* rmdnote

but I don't know what those look like, or if we need to install something.

**Comment by dsblank** [comment]
here they are visually: https://bookdown.org/yihui/bookdown/custom-blocks.html

**Comment by dsblank** [comment]
We can leave out the icons. They do draw your eye! (For better or worse)

PDF:

![screenshot from 2018-12-05 16-29-49](https://user-images.githubusercontent.com/168568/49545222-02827400-f8ab-11e8-9c51-0475e0908722.png)

HTML:
![screenshot from 2018-12-05 16-30-08](https://user-images.githubusercontent.com/168568/49545253-16c67100-f8ab-11e8-8bc7-33c454da149e.png)

**Comment by dsblank** [comment]
This is included in the PR: #111

**Comment by moorepants** [comment]
We can change icons later if we want or remove, I'd just include them for now since it works.

**Comment by willingc** [comment]
Perhaps we can use some of the font awesome images converted to png. An HTML example without styling:

<img width="806" alt="screenshot 2018-12-05 14 40 03" src="https://user-images.githubusercontent.com/2680980/49548822-c5fb4c00-f89b-11e8-8339-410c61fd54f9.png">

PDF with no styling:

<img width="946" alt="screenshot 2018-12-05 14 43 36" src="https://user-images.githubusercontent.com/2680980/49548949-2f7b5a80-f89c-11e8-8c64-e4921d5bd62a.png">

**Comment by dsblank** [comment]
Excellent suggestion! And beautiful output.

**Comment by dsblank** [comment]
Also, independently, we need to decide what keywords to use for what purpose.

**Comment by dsblank** [comment]
Can we close this and move discussion over to #115 ?
